# -*- coding: mbcs -*-
#
# Abaqus/CAE Release 2022 replay file
# Internal Version: 2021_09_15-22.27.30 176069
# Run by 795593 on Sat Jul 30 00:26:30 2022
#

# from driverUtils import executeOnCaeGraphicsStartup
# executeOnCaeGraphicsStartup()
#: Executing "onCaeGraphicsStartup()" in the site directory ...
from abaqus import *
from abaqusConstants import *
session.Viewport(name='Viewport: 1', origin=(0.0, 0.0), width=289.0, 
    height=158.694442749023)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].maximize()
from caeModules import *
from driverUtils import executeOnCaeStartup
executeOnCaeStartup()
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
openMdb(
    pathName='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/composite modal analysis.cae')
#: The model database "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae" has been opened.
session.viewports['Viewport: 1'].setValues(displayedObject=None)
p = mdb.models['No delamination CC'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['No delamination CC'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    optimizationTasks=OFF, geometricRestrictions=OFF, stopConditions=OFF)
del mdb.jobs['Job-1']
del mdb.jobs['Job-2']
del mdb.jobs['Job-3']
del mdb.jobs['Job-4']
del mdb.jobs['Job-5']
del mdb.jobs['Job-6']
del mdb.jobs['Job-7']
del mdb.jobs['Job-8']
del mdb.models['No delamination CC']
del mdb.models['x_a on L eq to zero point fifteen CF']
del mdb.models['x_a on L eq to zero point fifteen CC']
del mdb.models['x_a on L eq to zero point eighty five CF']
del mdb.models['x_a on L eq to zero point fifty CC']
del mdb.models['x_a on L eq to zero point thrity CC']
a = mdb.models['No delamination CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['x_a on L eq to zero point fifty CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.models.changeKey(fromName='x_a on L eq to zero point fifty CF', 
    toName='a on L eq to zero point zero point double zero five CF')
a = mdb.models['a on L eq to zero point zero point double zero five CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.models.changeKey(
    fromName='a on L eq to zero point zero point double zero five CF', 
    toName='a on L eq to zero point zero point zero five CF')
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['No delamination CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.Model(name='No delamination CC', 
    objectToCopy=mdb.models['No delamination CF'])
#: The model "No delamination CC" has been created.
a = mdb.models['No delamination CC'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.354745, 
    farPlane=0.449245, width=0.52448, height=0.237358, viewOffsetX=0.0128467, 
    viewOffsetY=-0.00229871)
a = mdb.models['No delamination CC'].rootAssembly
e1 = a.instances['Part-1-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#4 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['No delamination CC'].EncastreBC(name='BC-2', 
    createStepName='Initial', region=region, localCsys=None)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-1', model='No delamination CC', description='', 
    type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, queue=None, 
    memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-1'].submit(consistencyChecking=OFF)
#: The job input file "Job-1.inp" has been submitted for analysis.
#: Job Job-1: Analysis Input File Processor completed successfully.
#: Job Job-1: Abaqus/Standard completed successfully.
#: Job Job-1 completed successfully. 
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-1.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-1.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       2
#: Number of Node Sets:          1
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['No delamination CC'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['No delamination CF'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['No delamination CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.Job(name='Job-2', model='No delamination CF', description='', 
    type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, queue=None, 
    memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-2'].submit(consistencyChecking=OFF)
#: The job input file "Job-2.inp" has been submitted for analysis.
#: Job Job-2: Analysis Input File Processor completed successfully.
#: Job Job-2: Abaqus/Standard completed successfully.
#: Job Job-2 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-1.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-2.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-2.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     1
#: Number of Meshes:             1
#: Number of Element Sets:       2
#: Number of Node Sets:          1
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
p = mdb.models['No delamination CF'].parts['Part-1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point zero five CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[0], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0377683490514755, 
    0.0444360971450806), value=0.095)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.143918, 
    farPlane=0.204658, width=0.340128, height=0.153928, cameraPosition=(
    0.0417215, 0.0615914, 0.174288), cameraTarget=(0.0417215, 0.0615914, 0))
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.141327, 
    farPlane=0.188521, width=0.261996, height=0.118569, viewOffsetX=0.0131012, 
    viewOffsetY=0.00540635)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point zero five CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.FixedConstraint(entity=v[0])
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point zero five CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0128633677959442, 
    0.0170798823237419), value=0.01)
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0814592, 
    farPlane=0.0974262, width=0.0794506, height=0.0359561, 
    viewOffsetX=0.00256244, viewOffsetY=-0.00779109)
p1 = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point zero five CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.FixedConstraint(entity=v[0])
s2.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(
    -0.00622561573982239, 0.0195650886744261), value=0.01)
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
p1 = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point zero five CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[0], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0278161875903606, 
    0.0350420139729977), value=0.095)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.196587, 
    farPlane=0.253683, width=0.319721, height=0.144692, cameraPosition=(
    -0.0142095, 0.0498345, 0.225135), cameraTarget=(-0.0142095, 0.0498345, 0))
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point zero point zero five CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.141667, 
    farPlane=0.188181, width=0.232057, height=0.105019, viewOffsetX=0.0131863, 
    viewOffsetY=0.0117549)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a.deleteFeatures(('Beam1-1', 'Beam2-1', 'Beam3-1', 'Beam4-1', ))
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
a1.Instance(name='Beam1-1', part=p, dependent=ON)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
a1.Instance(name='Beam2-1', part=p, dependent=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.17174, 
    farPlane=0.21629, width=0.22064, height=0.0998524, viewOffsetX=0.00254878, 
    viewOffsetY=0.00272366)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a1.translate(instanceList=('Beam2-1', ), vector=(0.0, 0.095, 0.0003))
#: The instance Beam2-1 was translated by 0., 95.E-03, 300.E-06 with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.166017, 
    farPlane=0.222013, width=0.30917, height=0.139918, viewOffsetX=0.0378961, 
    viewOffsetY=0.0183686)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
a1.Instance(name='Beam3-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a1.translate(instanceList=('Beam3-1', ), vector=(0.0, 0.095, -0.0003))
#: The instance Beam3-1 was translated by 0., 95.E-03, -300.E-06 with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.181118, 
    farPlane=0.246735, width=0.206542, height=0.0934726, cameraPosition=(
    0.0278224, 0.0877383, 0.21025), cameraUpVector=(-0.957852, 0.285317, 
    0.0333751), cameraTarget=(0.0100125, 0.0525247, 0.000147447))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.165251, 
    farPlane=0.262602, width=0.188448, height=0.0852839, cameraPosition=(
    0.207969, -0.0281403, -0.00835703), cameraUpVector=(0.229429, 0.475215, 
    0.849431), cameraTarget=(0.010139, 0.0524433, -6.10761e-06))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.178146, 
    farPlane=0.249707, width=0.0666998, height=0.0301856, 
    viewOffsetX=0.0236097, viewOffsetY=0.013393)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.195687, 
    farPlane=0.245777, width=0.0732674, height=0.0331578, cameraPosition=(
    0.226668, 0.0144357, 0.0182091), cameraUpVector=(0.00908426, 0.508482, 
    0.861024), cameraTarget=(0.0168315, 0.0505414, -0.000899221), 
    viewOffsetX=0.0259344, viewOffsetY=0.0147118)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.187026, 
    farPlane=0.254438, width=0.167199, height=0.0756674, viewOffsetX=0.0221335, 
    viewOffsetY=0.0161029)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
a1.Instance(name='Beam4-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a1.translate(instanceList=('Beam4-1', ), vector=(0.0, 0.105, 0.0))
#: The instance Beam4-1 was translated by 0., 105.E-03, 0. with respect to the assembly coordinate system
session.viewports['Viewport: 1'].assemblyDisplay.setValues(
    renderBeamProfiles=ON, renderShellThickness=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.170207, 
    farPlane=0.277835, width=0.300489, height=0.135989, viewOffsetX=0.012506, 
    viewOffsetY=0.00207239)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.186383, 
    farPlane=0.261659, width=0.108033, height=0.0488915, 
    viewOffsetX=-0.0225853, viewOffsetY=-0.0139773)
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
e1 = a.instances['Beam1-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#1 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point zero point zero five CF'].boundaryConditions['BC-1'].setValues(
    region=region)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.18065, 
    farPlane=0.267392, width=0.185101, height=0.0837691, 
    viewOffsetX=-0.00624075, viewOffsetY=-0.00913696)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-3', model='a on L eq to zero point zero point zero five CF', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-3'].submit(consistencyChecking=OFF)
#: The job input file "Job-3.inp" has been submitted for analysis.
#: Error in job Job-3: in keyword *BOUNDARY, file "Job-3.inp", line 72: Unknown assembly node set _PICKEDSET32
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-3: THIS MODEL HAS EITHER INCORRECT OR NO ELEMENT DEFINITIONS.
#: Job Job-3: Analysis Input File Processor aborted due to errors.
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
#: Error in job Job-3: Analysis Input File Processor exited with an error - Please see the  Job-3.dat file for possible error messages if the file exists.
#: Job Job-3 aborted due to errors.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.17128, 
    farPlane=0.276762, width=0.287908, height=0.130641, viewOffsetX=0.016448, 
    viewOffsetY=-0.00546718)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(width=0.334214, 
    height=0.151653, viewOffsetX=0.0326011, viewOffsetY=0.018379)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF, mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam4']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam3']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam2']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
p.generateMesh()
a1 = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
mdb.jobs['Job-3'].submit(consistencyChecking=OFF)
#: The job input file "Job-3.inp" has been submitted for analysis.
#: Job Job-3: Analysis Input File Processor completed successfully.
#: Job Job-3: Abaqus/Standard completed successfully.
#: Job Job-3 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-2.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-3.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-3.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    UNDEFORMED, ))
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
a = mdb.models['a on L eq to zero point zero point zero five CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-3.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-2.odb')
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
mdb.Model(name='a on L eq to zero point zero point zero five CC', 
    objectToCopy=mdb.models['a on L eq to zero point zero point zero five CF'])
#: The model "a on L eq to zero point zero point zero five CC" has been created.
p = mdb.models['a on L eq to zero point zero point zero five CC'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['a on L eq to zero point zero point zero five CC'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
a = mdb.models['a on L eq to zero point zero point zero five CC'].rootAssembly
e1 = a.instances['Beam4-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#4 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point zero point zero five CC'].EncastreBC(
    name='BC-2', createStepName='Initial', region=region, localCsys=None)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-4', model='a on L eq to zero point zero point zero five CC', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-4'].submit(consistencyChecking=OFF)
#: The job input file "Job-4.inp" has been submitted for analysis.
#: Job Job-4: Analysis Input File Processor completed successfully.
#: Job Job-4: Abaqus/Standard completed successfully.
#: Job Job-4 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-2.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-4.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-4.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=4)
p = mdb.models['a on L eq to zero point zero point zero five CC'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p1 = mdb.models['a on L eq to zero point zero point zero five CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
mdb.Model(name='a on L eq to zero point zero point one CF', 
    objectToCopy=mdb.models['a on L eq to zero point zero point zero five CF'])
#: The model "a on L eq to zero point zero point one CF" has been created.
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.delete(objectList=(d[1], ))
s2.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.049276664853096, 
    0.0493592470884323), value=0.09)
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
p.regenerate()
p1 = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[0], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(
    -0.00795512273907661, 0.00495122699066997), value=0.02)
s1.unsetPrimaryObject()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0420572, 
    farPlane=0.0473855, width=0.0297304, height=0.0134547, 
    viewOffsetX=0.00256601, viewOffsetY=0.000228511)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.037822, 
    farPlane=0.0516207, width=0.0765475, height=0.0346423, 
    viewOffsetX=0.014865, viewOffsetY=0.0083669)
p1 = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.delete(objectList=(d[0], ))
s2.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(
    -0.00385358789935708, 0.00546753872185946), value=0.02)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0503152, 
    farPlane=0.0682278, width=0.100305, height=0.0453937, cameraPosition=(
    0.0182724, 0.0146703, 0.0592715), cameraTarget=(0.0182724, 0.0146703, 0))
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0397342, 
    farPlane=0.0497086, width=0.0554776, height=0.0251069, 
    viewOffsetX=0.004787, viewOffsetY=0.00469169)
p1 = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point zero point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[1], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0599330253899097, 
    0.044091384857893), value=0.09)
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point zero point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
p.regenerate()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.171682, 
    farPlane=0.216647, width=0.249621, height=0.112968, viewOffsetX=0.00461957, 
    viewOffsetY=0.000879353)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a.deleteFeatures(('Beam1-1', 'Beam2-1', 'Beam3-1', 'Beam4-1', ))
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
a1.Instance(name='Beam1-1', part=p, dependent=ON)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
a1.Instance(name='Beam2-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.translate(instanceList=('Beam2-1', ), vector=(0.0, 0.09, 0.0003))
#: The instance Beam2-1 was translated by 0., 90.E-03, 300.E-06 with respect to the assembly coordinate system
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
a1.Instance(name='Beam3-1', part=p, dependent=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.197009, 
    farPlane=0.25023, width=0.288761, height=0.130681, viewOffsetX=0.0219798, 
    viewOffsetY=-0.00646174)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.translate(instanceList=('Beam3-1', ), vector=(0.0, 0.09, -0.0003))
#: The instance Beam3-1 was translated by 0., 90.E-03, -300.E-06 with respect to the assembly coordinate system
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
a1.Instance(name='Beam4-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.translate(instanceList=('Beam4-1', ), vector=(0.0, 0.11, 0.0))
#: The instance Beam4-1 was translated by 0., 110.E-03, 0. with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.198885, 
    farPlane=0.248354, width=0.227597, height=0.103001, cameraPosition=(0.01, 
    0.055, 0.22362), cameraUpVector=(-0.995903, -0.0904254, 0), cameraTarget=(
    0.01, 0.055, 0))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.169964, 
    farPlane=0.262083, width=0.194501, height=0.0880231, cameraPosition=(
    0.181645, 0.0907612, 0.138798), cameraUpVector=(-0.504405, 0.748206, 
    0.431003), cameraTarget=(0.00999961, 0.0549999, 1.93715e-07))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.166128, 
    farPlane=0.32713, width=0.190112, height=0.0860367, cameraPosition=(
    0.182381, -0.0578063, 0.0816967), cameraUpVector=(-0.395399, 0.0419247, 
    0.917552), cameraTarget=(0.00997371, 0.0602242, 0.00200813))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.164606, 
    farPlane=0.331015, width=0.18837, height=0.0852484, cameraPosition=(
    0.192026, -0.0646172, 0.040108), cameraUpVector=(-0.202185, 0.0358975, 
    0.978689), cameraTarget=(0.0108736, 0.0595888, -0.0018719))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.198995, 
    farPlane=0.258358, width=0.227723, height=0.103058, cameraPosition=(
    0.222854, 0.067634, 0.081638), cameraUpVector=(-0.314906, 0.41493, 
    0.85362), cameraTarget=(0.013883, 0.0724991, 0.00218223))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.17687, 
    farPlane=0.295716, width=0.202404, height=0.0915995, cameraPosition=(
    0.219785, 0.009212, 0.0629126), cameraUpVector=(-0.129923, 0.443156, 
    0.886979), cameraTarget=(0.0138151, 0.0712072, 0.00176815))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.180625, 
    farPlane=0.29196, width=0.199117, height=0.0901121, viewOffsetX=0.00971539, 
    viewOffsetY=0.00640639)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
p.generateMesh()
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF, 
    interactions=ON, constraints=ON, connectors=ON, engineeringFeatures=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF)
mdb.Job(name='Job-5', model='a on L eq to zero point zero point one CF', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-5'].submit(consistencyChecking=OFF)
#: The job input file "Job-5.inp" has been submitted for analysis.
#: Error in job Job-5: in keyword *BOUNDARY, file "Job-5.inp", line 2648: Unknown assembly node set _PICKEDSET32
#: Error in job Job-5: NODE SET ASSEMBLY__PICKEDSET32 HAS NOT BEEN DEFINED
#: Error in job Job-5: A BOUNDARY CONDITION HAS BEEN SPECIFIED ON NODE SET ASSEMBLY__PICKEDSET32 BUT THIS NODE SET IS NOT ACTIVE IN THE MODEL
#: Error in job Job-5: NODE SET ASSEMBLY__PICKEDSET32 HAS NOT BEEN DEFINED
#: Error in job Job-5: NODE SET ASSEMBLY__PICKEDSET32 HAS NOT BEEN DEFINED
#: Error in job Job-5: NODE SET ASSEMBLY__PICKEDSET32 HAS NOT BEEN DEFINED
#: Job Job-5: Analysis Input File Processor aborted due to errors.
#: Error in job Job-5: Analysis Input File Processor exited with an error - Please see the  Job-5.dat file for possible error messages if the file exists.
#: Job Job-5 aborted due to errors.
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
e1 = a.instances['Beam1-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#1 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point zero point one CF'].boundaryConditions['BC-1'].setValues(
    region=region)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.jobs['Job-5'].submit(consistencyChecking=OFF)
#: The job input file "Job-5.inp" has been submitted for analysis.
#: Job Job-5: Analysis Input File Processor completed successfully.
#: Job Job-5: Abaqus/Standard completed successfully.
#: Job Job-5 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-4.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          3
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=ON, 
    constraints=ON, connectors=ON, engineeringFeatures=ON)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam1 to Beam2'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam1 to Beam3'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam4 to Beam2'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam4 to Beam3'].setValues(
    positionTolerance=0.001)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF)
mdb.jobs['Job-5'].submit(consistencyChecking=OFF)
#: The job input file "Job-5.inp" has been submitted for analysis.
#: Job Job-5: Analysis Input File Processor completed successfully.
#: Job Job-5: Abaqus/Standard completed successfully.
#: Job Job-5 completed successfully. 
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          3
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.191065, 
    farPlane=0.28152, width=0.0735673, height=0.033382, viewOffsetX=0.01571, 
    viewOffsetY=0.00876918)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.191478, 
    farPlane=0.281106, width=0.0737267, height=0.0334543, cameraPosition=(
    0.218493, 0.00959636, 0.0676534), cameraUpVector=(-0.0459278, 0.619954, 
    0.783293), cameraTarget=(0.0125234, 0.0715916, 0.00650892), 
    viewOffsetX=0.015744, viewOffsetY=0.00878816)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.216802, 
    farPlane=0.255686, width=0.0834776, height=0.0378789, cameraPosition=(
    0.119419, 0.0593941, 0.20694), cameraUpVector=(-0.538193, 0.755798, 
    0.372983), cameraTarget=(0.00693746, 0.0743881, 0.0142517), 
    viewOffsetX=0.0178263, viewOffsetY=0.00995045)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.21721, 
    farPlane=0.254293, width=0.0836347, height=0.0379502, cameraPosition=(
    0.148971, 0.0658353, 0.189114), cameraUpVector=(-0.523318, 0.723314, 
    0.450506), cameraTarget=(0.0100719, 0.0743651, 0.0140706), 
    viewOffsetX=0.0178599, viewOffsetY=0.00996918)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.20803, 
    farPlane=0.263474, width=0.190477, height=0.086431, viewOffsetX=0.0165592, 
    viewOffsetY=0.0165105)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.169355, 
    farPlane=0.297827, width=0.155066, height=0.0703626, cameraPosition=(
    0.182418, -0.0104354, 0.11382), cameraUpVector=(-0.153185, 0.648756, 
    0.745419), cameraTarget=(0.00510992, 0.0721942, 0.00546879), 
    viewOffsetX=0.0134807, viewOffsetY=0.0134411)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.175164, 
    farPlane=0.213165, width=0.210976, height=0.0957327, 
    viewOffsetX=0.00328711, viewOffsetY=-0.0066173)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0513874, 
    farPlane=0.0617497, width=0.0575185, height=0.0260996, 
    viewOffsetX=-0.000739957, viewOffsetY=-0.0014337)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0519863, 
    farPlane=0.0611508, width=0.0512062, height=0.0232354, 
    viewOffsetX=0.000184332, viewOffsetY=-0.00112387)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.184277, 
    farPlane=0.282904, width=0.035924, height=0.0163009, viewOffsetX=0.0188411, 
    viewOffsetY=0.00989959)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
p.deleteMesh()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
p.deleteMesh()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.18386, 
    farPlane=0.283321, width=0.0405646, height=0.0184066, 
    viewOffsetX=0.0188417, viewOffsetY=0.0100673)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.181922, 
    farPlane=0.285259, width=0.0623126, height=0.0282001, 
    viewOffsetX=0.0288232, viewOffsetY=0.00902584)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.211477, 
    farPlane=0.263663, width=0.0724358, height=0.0327815, cameraPosition=(
    0.232499, 0.0461834, 0.0692477), cameraUpVector=(-0.221033, 0.476486, 
    0.850944), cameraTarget=(0.020674, 0.0691567, 0.00136269), 
    viewOffsetX=0.0335058, viewOffsetY=0.0104922)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.200725, 
    farPlane=0.274415, width=0.185789, height=0.0840805, viewOffsetX=0.036005, 
    viewOffsetY=0.0132577)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.193937, 
    farPlane=0.281203, width=0.260203, height=0.11807, viewOffsetX=0.0445861, 
    viewOffsetY=0.0132532)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
p.regenerate()
#: 
#: Point 1: 0., 0., 0.  Point 2: 0., 90.E-03, 0.
#:    Distance: 90.E-03  Components: 0., 90.E-03, 0.
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
#: 
#: Point 1: 20.E-03, 0., 0.  Point 2: 20.E-03, 0., 0.
#:    Distance: 0.  Components: 0., 0., 0.
#: 
#: Point 1: 20.E-03, 0., 0.  Point 2: 20.E-03, 0., 0.
#:    Distance: 0.  Components: 0., 0., 0.
#: 
#: Point 1: 20.E-03, 90.E-03, 0.  Point 2: 20.E-03, 0., 0.
#:    Distance: 90.E-03  Components: 0., -90.E-03, 0.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.194208, 
    farPlane=0.280932, width=0.230848, height=0.104472, viewOffsetX=0.0252872, 
    viewOffsetY=0.0136028)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
p.deleteMesh()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
p.deleteMesh()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.200784, 
    farPlane=0.274357, width=0.164647, height=0.0747104, viewOffsetX=0.0297255, 
    viewOffsetY=0.0106362)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam4']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
p.generateMesh()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam2']
p.generateMesh()
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point zero point one CF'].parts['Beam3']
p.generateMesh()
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a1 = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
a1.regenerate()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.196209, 
    farPlane=0.278417, width=0.235139, height=0.106697, viewOffsetX=0.0249323, 
    viewOffsetY=0.00836655)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF, 
    interactions=ON, constraints=ON, connectors=ON, engineeringFeatures=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam1 to Beam2'].setValues(
    positionTolerance=0.002)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam1 to Beam3'].setValues(
    positionTolerance=0.002)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam4 to Beam2'].setValues(
    positionTolerance=0.002)
mdb.models['a on L eq to zero point zero point one CF'].constraints['Beam4 to Beam3'].setValues(
    positionTolerance=0.002)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF)
mdb.jobs['Job-5'].submit(consistencyChecking=OFF)
#: The job input file "Job-5.inp" has been submitted for analysis.
#: Job Job-5: Analysis Input File Processor completed successfully.
#: Job Job-5: Abaqus/Standard completed successfully.
#: Job Job-5 completed successfully. 
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=2)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=5)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=4)
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=5)
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
mdb.Model(name='a on L eq to zero point zero point one CC', 
    objectToCopy=mdb.models['a on L eq to zero point zero point one CF'])
#: The model "a on L eq to zero point zero point one CC" has been created.
a = mdb.models['a on L eq to zero point zero point one CC'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['a on L eq to zero point zero point one CC'].rootAssembly
e1 = a.instances['Beam4-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#4 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point zero point one CC'].EncastreBC(name='BC-2', 
    createStepName='Initial', region=region, localCsys=None)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-6', model='a on L eq to zero point zero point one CC', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-6'].submit(consistencyChecking=OFF)
#: The job input file "Job-6.inp" has been submitted for analysis.
#: Job Job-6: Analysis Input File Processor completed successfully.
#: Job Job-6: Abaqus/Standard completed successfully.
#: Job Job-6 completed successfully. 
a = mdb.models['a on L eq to zero point zero point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.Model(name='a on L eq to zero point twenty point one CF', 
    objectToCopy=mdb.models['a on L eq to zero point zero point one CF'])
#: The model "a on L eq to zero point twenty point one CF" has been created.
a = mdb.models['a on L eq to zero point twenty point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.models.changeKey(fromName='a on L eq to zero point twenty point one CF', 
    toName='a on L eq to zero point two point one CF')
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=ON, 
    engineeringFeatures=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
session.viewports['Viewport: 1'].partDisplay.setValues(sectionAssignments=OFF, 
    engineeringFeatures=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
#: 
#: Point 1: 0., 0., 0.  Point 2: 0., 20.E-03, 0.
#:    Distance: 20.E-03  Components: 0., 20.E-03, 0.
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point two point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.delete(objectList=(d[1], ))
s2.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(
    -0.00612892303615808, 0.00964119844138622), value=0.04)
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0477374, 
    farPlane=0.0653997, width=0.0882495, height=0.0399381, 
    viewOffsetX=0.00121394, viewOffsetY=0.0106934)
p1 = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point two point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[1], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(
    -0.00798092596232891, 0.0098695270717144), value=0.04)
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.regenerate()
#: Warning: Failed to attach mesh to part geometry.
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.0476228, 
    farPlane=0.0655143, width=0.0992291, height=0.044907, 
    viewOffsetX=0.00870878, viewOffsetY=0.0116518)
p1 = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point two point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s2 = mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
g, v, d, c = s2.geometry, s2.vertices, s2.dimensions, s2.constraints
s2.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s2, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s2.delete(objectList=(d[2], ))
s2.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0488452166318893, 
    0.0348720028996468), value=0.08)
s2.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.features['Shell planar-1'].setValues(sketch=s2)
del mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.regenerate()
p1 = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
s = p.features['Shell planar-1'].sketch
mdb.models['a on L eq to zero point two point one CF'].ConstrainedSketch(
    name='__edit__', objectToCopy=s)
s1 = mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
g, v, d, c = s1.geometry, s1.vertices, s1.dimensions, s1.constraints
s1.setPrimaryObject(option=SUPERIMPOSE)
p.projectReferencesOntoSketch(sketch=s1, 
    upToFeature=p.features['Shell planar-1'], filter=COPLANAR_EDGES)
s1.delete(objectList=(d[2], ))
s1.ObliqueDimension(vertex1=v[0], vertex2=v[1], textPoint=(-0.0537392571568489, 
    0.050577737390995), value=0.08)
s1.unsetPrimaryObject()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.features['Shell planar-1'].setValues(sketch=s1)
del mdb.models['a on L eq to zero point two point one CF'].sketches['__edit__']
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.regenerate()
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a.deleteFeatures(('Beam1-1', 'Beam2-1', 'Beam3-1', 'Beam4-1', ))
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
a1.Instance(name='Beam1-1', part=p, dependent=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
a1.Instance(name='Beam2-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.translate(instanceList=('Beam2-1', ), vector=(0.0, 0.08, 0.0003))
#: The instance Beam2-1 was translated by 0., 80.E-03, 300.E-06 with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.268971, 
    farPlane=0.445125, width=0.310793, height=0.140652, cameraPosition=(
    0.123713, -0.178573, 0.241315), cameraUpVector=(0.211151, 0.694486, 
    0.687825))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.281214, 
    farPlane=0.432883, width=0.324939, height=0.147054, cameraPosition=(
    0.123713, -0.178573, 0.241315), cameraUpVector=(-0.790117, 0.186597, 
    0.583864), cameraTarget=(0.00999999, 0.095, 6.98492e-09))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.309346, 
    farPlane=0.424136, width=0.357446, height=0.161765, cameraPosition=(
    0.277683, -0.0352653, 0.232965), cameraUpVector=(-0.684338, -0.363547, 
    0.632071), cameraTarget=(-0.000805978, 0.0849423, 0.000586039))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.306259, 
    farPlane=0.427224, width=0.353879, height=0.160151, cameraPosition=(
    0.277683, -0.0352653, 0.232965), cameraUpVector=(-0.570742, 0.211528, 
    0.793416), cameraTarget=(-0.000805976, 0.0849423, 0.00058604))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.301553, 
    farPlane=0.425375, width=0.348441, height=0.15769, cameraPosition=(
    0.342922, -0.0364069, 0.111656), cameraUpVector=(-0.274738, 0.0540456, 
    0.959999), cameraTarget=(-0.00353936, 0.0849901, 0.00566866))
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.317123, 
    farPlane=0.409805, width=0.201436, height=0.0911617, 
    viewOffsetX=-0.00691576, viewOffsetY=-0.000530024)
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
a1.Instance(name='Beam3-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.translate(instanceList=('Beam3-1', ), vector=(0.0, 0.08, -0.0003))
#: The instance Beam3-1 was translated by 0., 80.E-03, -300.E-06 with respect to the assembly coordinate system
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
a1.Instance(name='Beam4-1', part=p, dependent=ON)
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.translate(instanceList=('Beam4-1', ), vector=(0.0, 0.12, 0.0))
#: The instance Beam4-1 was translated by 0., 120.E-03, 0. with respect to the assembly coordinate system
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.203219, 
    farPlane=0.329232, width=0.227368, height=0.102897, 
    viewOffsetX=-0.00775134, viewOffsetY=0.00492164)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=ON, 
    constraints=ON, connectors=ON, engineeringFeatures=ON)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, interactions=OFF, constraints=OFF, 
    engineeringFeatures=OFF)
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
e1 = a.instances['Beam1-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#1 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point two point one CF'].boundaryConditions['BC-1'].setValues(
    region=region)
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb'])
odb = session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb']
session.viewports['Viewport: 1'].setValues(displayedObject=odb)
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-7', model='a on L eq to zero point two point one CF', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-7'].submit(consistencyChecking=OFF)
#: The job input file "Job-7.inp" has been submitted for analysis.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_LEFT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM2-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_RIGHT DOES NOT EXIST.
#: Error in job Job-7: THE SECONDARY SURFACE ASSEMBLY_BEAM3-1_TOP DOES NOT EXIST.
#: Job Job-7: Analysis Input File Processor aborted due to errors.
#: Error in job Job-7: Analysis Input File Processor exited with an error - Please see the  Job-7.dat file for possible error messages if the file exists.
#: Job Job-7 aborted due to errors.
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.generateMesh()
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.regenerate()
session.viewports['Viewport: 1'].view.setValues(nearPlane=0.215626, 
    farPlane=0.316825, width=0.0792076, height=0.0359413, 
    viewOffsetX=0.0251081, viewOffsetY=0.00146845)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
mdb.jobs['Job-7'].submit(consistencyChecking=OFF)
#: The job input file "Job-7.inp" has been submitted for analysis.
#: Job Job-7: Analysis Input File Processor completed successfully.
#: Job Job-7: Abaqus/Standard completed successfully.
#: Job Job-7 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-5.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-7.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-7.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].odbDisplay.setFrame(step=0, frame=2)
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.seedPart(size=0.001, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam4']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.seedPart(size=0.001, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam3']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.seedPart(size=0.001, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam2']
p.generateMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.deleteMesh()
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.seedPart(size=0.001, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
p.generateMesh()
a1 = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
a1.regenerate()
a = mdb.models['a on L eq to zero point two point one CF'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(mesh=OFF, 
    interactions=ON, constraints=ON, connectors=ON, engineeringFeatures=ON)
session.viewports['Viewport: 1'].assemblyDisplay.meshOptions.setValues(
    meshTechnique=OFF)
mdb.models['a on L eq to zero point two point one CF'].constraints['Beam1 to Beam2'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point two point one CF'].constraints['Beam1 to Beam3'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point two point one CF'].constraints['Beam4 to Beam2'].setValues(
    positionTolerance=0.001)
mdb.models['a on L eq to zero point two point one CF'].constraints['Beam4 to Beam3'].setValues(
    positionTolerance=0.001)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(interactions=OFF, 
    constraints=OFF, connectors=OFF, engineeringFeatures=OFF)
mdb.jobs['Job-7'].submit(consistencyChecking=OFF)
#: The job input file "Job-7.inp" has been submitted for analysis.
#: Job Job-7: Analysis Input File Processor completed successfully.
#: Job Job-7: Abaqus/Standard completed successfully.
#: Job Job-7 completed successfully. 
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-7.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-7.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=OFF)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=OFF)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=ON)
p = mdb.models['a on L eq to zero point two point one CF'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
mdb.Model(name='a on L eq to zero point two point one CC', 
    objectToCopy=mdb.models['a on L eq to zero point two point one CF'])
#: The model "a on L eq to zero point two point one CC" has been created.
p = mdb.models['a on L eq to zero point two point one CC'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
a = mdb.models['a on L eq to zero point two point one CC'].rootAssembly
session.viewports['Viewport: 1'].setValues(displayedObject=a)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=ON, bcs=ON, 
    predefinedFields=ON, connectors=ON)
a = mdb.models['a on L eq to zero point two point one CC'].rootAssembly
e1 = a.instances['Beam4-1'].edges
edges1 = e1.getSequenceFromMask(mask=('[#4 ]', ), )
region = regionToolset.Region(edges=edges1)
mdb.models['a on L eq to zero point two point one CC'].EncastreBC(name='BC-2', 
    createStepName='Initial', region=region, localCsys=None)
session.viewports['Viewport: 1'].assemblyDisplay.setValues(loads=OFF, bcs=OFF, 
    predefinedFields=OFF, connectors=OFF)
mdb.Job(name='Job-8', model='a on L eq to zero point two point one CC', 
    description='', type=ANALYSIS, atTime=None, waitMinutes=0, waitHours=0, 
    queue=None, memory=90, memoryUnits=PERCENTAGE, getMemoryFromAnalysis=True, 
    explicitPrecision=SINGLE, nodalOutputPrecision=SINGLE, echoPrint=OFF, 
    modelPrint=OFF, contactPrint=OFF, historyPrint=OFF, userSubroutine='', 
    scratch='', resultsFormat=ODB, numThreadsPerMpiProcess=1, 
    multiprocessingMode=DEFAULT, numCpus=1, numGPUs=0)
mdb.jobs['Job-8'].submit(consistencyChecking=OFF)
#: The job input file "Job-8.inp" has been submitted for analysis.
#: Job Job-8: Analysis Input File Processor completed successfully.
#: Job Job-8: Abaqus/Standard completed successfully.
#: Job Job-8 completed successfully. 
session.viewports['Viewport: 1'].setValues(
    displayedObject=session.odbs['D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-7.odb'])
o3 = session.openOdb(
    name='D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-8.odb')
#: Model: D:/Delamination-detection-in-composite-laminates-using-deep-learning/Abacus models/modal analysis/3d shell planner/a diffrence/Job-8.odb
#: Number of Assemblies:         1
#: Number of Assembly instances: 0
#: Number of Part instances:     4
#: Number of Meshes:             4
#: Number of Element Sets:       5
#: Number of Node Sets:          2
#: Number of Steps:              1
session.viewports['Viewport: 1'].setValues(displayedObject=o3)
session.viewports['Viewport: 1'].makeCurrent()
session.viewports['Viewport: 1'].odbDisplay.display.setValues(plotState=(
    CONTOURS_ON_DEF, ))
session.viewports['Viewport: 1'].partDisplay.setValues(mesh=ON)
session.viewports['Viewport: 1'].partDisplay.meshOptions.setValues(
    meshTechnique=ON)
session.viewports['Viewport: 1'].partDisplay.geometryOptions.setValues(
    referenceRepresentation=OFF)
p = mdb.models['a on L eq to zero point two point one CC'].parts['Beam1']
session.viewports['Viewport: 1'].setValues(displayedObject=p)
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
mdb.save()
#: The model database has been saved to "D:\Delamination-detection-in-composite-laminates-using-deep-learning\Abacus models\modal analysis\3d shell planner\a diffrence\composite modal analysis.cae".
